spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;
      username: sa
    data: classpath:data-h2.sql
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.type: trace